### PR TITLE
Simple check if locale dir is available at the system

### PR DESCRIPTION
**Pull request by avlach**
I just installed on my system (Arch Linux w/ XFCE desktop environment). Installation fails since it cannot detect any locale directory so I had to add this simple check to proceed with the installation. 
Maybe this prevents some non Ubuntu users with similar configuration from installing the application. 
Thanks for your effort! Very useful app.

### CODE REVIEW

**Comment by yktoo** [comment]
Hmm, catching _any_ exception is a rather crude solution to the issue. The `locale` dir is in the source tree, and it is rolled into the source tarball, so it should always be present.

How exactly did you install the app?

**Comment by avlach** [comment]
True, that was a heavy hand solution. 
I tried downloading the release file (.tar.gz) and also cloning master branch then following the install instructions (sudo python setup.py install). 
I couldn't find `locale` in either the tarfile or the repo folder so I assumed something has to do with my system.

**Comment by yktoo** [comment]
That's correct, `locale` is not in the source tree initially, it is generated by `build_package`. I will think how this is to be resolved properly. Will close the issue for now.

**Comment by yktoo** [comment]
I will add instructions on how to install from the repo.

**Pull request closed without merging**
